services:
  linktiles:
    image: haumea/linktiles:0.0.5
    x-tl: x
    networks:
      - linktiles
      - rathole
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 5001
      RATHOLE_VIRTUAL_HOST: linktiles.cloud.haondt.dev
      LT_DB_ENGINE: redis
      LT_DB_HOST: linktiles-redis
      LT_SECRET_KEY: "{{ linktiles__secret_key }}"
      LT_ENABLE_AUTH_PROXY: "true"
      LT_AUTH_PROXY_USERNAME_HEADER: "HTTP_REMOTE_USER"
      LT_AUTH_PROXY_LOGOUT_URL: https://auth.haondt.dev/logout
  linktiles-redis:
    image: redis:latest
    x-tl: x
    networks:
      - linktiles

networks:
  linktiles:

