services:
  jobs:
    networks:
      - jobs
      - gabbro_nginx
      - deployments-gabbro_glance
      - deployments-gabbro_mimir
    build:
      context: jobs
    x-tl: x
    healthcheck:
      test: curl --fail http://localhost:1880/hc || exit 1
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 60s
    volumes:
      - ./jobs/settings.js:/data/settings.js
      - /mnt/celery/gabbro/jobs/nodered_data/:/data
    environment:
      VIRTUAL_PORT: 1880
      VIRTUAL_HOST: "jobs.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp
      TWITCH_CLIENT_ID: "{{ jobs__twitch__client_id }}"
      TWITCH_CLIENT_SECRET: "{{ jobs__twitch__client_secret }}"
      TWITCH_REDIRECT_URL: "http://localhost"
      HC_PING_KEY: "{{ hc__ping_key }}"
      HC_BASE_URL: "{{ hc__base_url }}"
      GITLAB_TOKEN: "{{ jobs__gitlab_token }}"


  jobs-redis: 
    image: docker.io/library/redis:latest@sha256:b0341dc2e0ce47beb7fcef80089b4d469b10ae94fbbea50072b878d7c88de487
    x-tl: +!
    networks:
      - jobs
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  jobs-redis-insight:
    image: docker.io/redis/redisinsight:latest@sha256:b7aa18e73329ebb2e3d9e949b8d35193bf5415ef35c16fd9a50e6f832922b296
    x-tl: +!
    networks:
      - jobs
      - gabbro_nginx
    environment:
      VIRTUAL_PORT: 5540
      VIRTUAL_HOST: "jobs-redis.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp
    volumes:
      - jobs-redis-insight-data:/data

networks:
  jobs:
  gabbro_nginx:
    external: true
  deployments-gabbro_glance:
    external: true
  deployments-gabbro_mimir:
    external: true
volumes:
  jobs-redis-insight-data:
