services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:latest@sha256:44b6ead7489410fb9a6e11e0efee7bfc9fabaa2921a3fc1588fb4615f1e78e17
    x-tl: +!
    networks:
      - gabbro_nginx
    volumes:
      - /mnt/celery/gabbro/lubelogger/data/:/App/data
      - /mnt/celery/gabbro/lubelogger/keys/:/root/.aspnet/DataProtection-Keys
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "lubelogger.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp

      LC_ALL: en_CA
      LANG: en_CA


