services:
  nginx:
    image: docker.io/nginxproxy/nginx-proxy:latest@sha256:5065797ce9ec3e60704e9bfec1cba79dfa981f4612154cf48f252df51419c9fa
    x-tl: +!
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - nginx

  nginx-acme:
    image: docker.io/nginxproxy/acme-companion:latest@sha256:ed9fad2339bdc80bf211f352c82e680d3eaa315f6e8d5975a39d0775f99e6861
    x-tl: +!
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-acmesh:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "{{ cf__default_email }}"
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Token: {{ cf__token }}
        CF_Zone_ID: {{ cf__zone_id }}
        CF_Account_ID: {{ cf__account_id }}

networks:
  nginx:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acmesh:


