services:
  nginx:
    image: docker.io/nginxproxy/nginx-proxy:latest@sha256:452f458e74bee0da7083faab6896034ae6b8be9167627956e314d055ad329edd
    x-tl: +!
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - nginx

  nginx-acme:
    image: docker.io/nginxproxy/acme-companion:latest@sha256:b4bf2cea4b1ce732cc5e93e6a77b34895a8e77f462ede7d9180fcdef3d828b3d
    x-tl: +!
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-acmesh:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "{{ cf__default_email }}"
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Token: {{ cf__token }}
        CF_Zone_ID: {{ cf__zone_id }}
        CF_Account_ID: {{ cf__account_id }}

networks:
  nginx:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acmesh:


