services:
  website:
    image: registry.gitlab.com/haondt/cicd/registry/website:3.0.0
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: haondt.dev
      LETSENCRYPT_HOST: haondt.dev
      VIRTUAL_PORT: 8000
