services:
  website-haondt:
    image: registry.gitlab.com/haondt/cicd/registry/website:3.0.3
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: haondt.dev
      VIRTUAL_PORT: 8000
      HTTPS_METHOD: nohttp

