services:
  docker_slim_exporter:
    image: docker.io/haumea/docker_slim_exporter:0.0.3@sha256:c0664cd21ef32da6fdb11ced30b176466870b5a8e3c45982f45e52cc68a8584e
    x-tl: +!
    networks:
      - alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      INCLUDE_STOPPED: true
      DISABLE_DEFAULT_METRICS: true
      INCLUDE_LABELS: true
