services:
  docker_slim_exporter:
    image: docker.io/haumea/docker_slim_exporter:0.0.2@sha256:c95fd8b1965bea93b4c7f53ed76be608b61a32c3a9cef0a5c18a3c8bc3e4b365
    x-tl: +!
    networks:
      - alloy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      INCLUDE_STOPPED: true
      DISABLE_DEFAULT_METRICS: true
      INCLUDE_LABELS: true
