services:
  linkding:
    image: docker.io/sissbruecker/linkding:latest@sha256:e498575b84f5e84d36ed69ed0036ff33916b3d1bb5908f1892ac935e1754590d
    x-tl: +!
    networks:
      - gabbro_nginx
      - glance
    volumes:
      - linkding-data:/etc/linkding/data
    env_file:
      - ./linkding/linkding.env
    environment:
      VIRTUAL_PORT: 9090
      VIRTUAL_HOST: "linkding.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp
volumes:
  linkding-data:
networks:
  gabbro_nginx:
    external: true
