target: all

multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /mimir/tsdb-sync
  filesystem:
    dir: /mimir/data/tsdb
  tsdb:
    dir: /mimir/tsdb

compactor:
  data_dir: /mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist
limits:
  compactor_blocks_retention_period: 14d

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /mimir/rules

server:
  http_listen_port: 8080
  log_level: info

store_gateway:
  sharding_ring:
    replication_factor: 1

