services:
  jobs:
    networks:
      - jobs
      - gabbro_nginx
    build:
      context: jobs
    volumes:
      - ./jobs/settings.js:/data/settings.js
      - /mnt/celery/gabbro/jobs/nodered_data/:/data
    environment:
      VIRTUAL_HOST: jobs.gabbro.local.haondt.dev
      VIRTUAL_PORT: 1880
      LETSENCRYPT_HOST: "*.gabbro.local.haondt.dev"
  jobs-redis: 
    image: redis
    networks:
      - jobs


networks:
  gabbro_nginx:
    external: true
  jobs:
