services:
  jobs:
    networks:
      - nginx
      - midas
    build:
      context: jobs
    volumes:
      - ./jobs/settings.js:/data/settings.js
      - /mnt/celery/gabbro/jobs/nodered_data/:/data
    environment:
      VIRTUAL_HOST: "jobs.{{ LETSENCRYPT_HOST }}"
      VIRTUAL_PORT: 1880
      LETSENCRYPT_HOST: "*.{{ LETSENCRYPT_HOST }}"
  jobs-redis: 
    image: redis
    networks:
      - jobs


networks:
  jobs:
