services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest@sha256:2868ae5e3dd9065ea3b1e44b4214b33b02b7ce5ebcb9e4f33e1132b75007f39c
    x-tl: +!
    networks:
      - wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      PEERS: 1
    volumes:
      - wireguard-data:/config
    ports:
      - 51820:51820/udp

volumes:
  wireguard-data:

networks:
  wireguard:

