services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest@sha256:fd4a95e233a90070372ccf7f488ef005932eb16ca1b0bd40afbdbb3dae9a3951
    x-tl: +!
    networks:
      - wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      PEERS: 1
    volumes:
      - wireguard-data:/config
    ports:
      - 51820:51820/udp

volumes:
  wireguard-data:

networks:
  wireguard:

