services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest@sha256:bf03578ef7318ccc7675b4a82beac4d35cd0da2253194f6b6ecf61656b40f0ee
    x-tl: +!
    networks:
      - wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      PEERS: 1
    volumes:
      - wireguard-data:/config
    ports:
      - 51820:51820/udp

volumes:
  wireguard-data:

networks:
  wireguard:

