services:
  elysium-stage:
    networks:
      - nginx
      - elysium-stage
    image: registry.gitlab.com/haondt/cicd/registry/elysium:0.0.5
    x-tl: x
    depends_on:
      - elysium-stage-silo
    environment:
      VIRTUAL_HOST: elysium-stage.haondt.dev
      VIRTUAL_PORT: 8080
    env_file:
      - ./elysium-stage/elysium.env
      - ./elysium-stage/shared.env
  elysium-stage-silo:
    networks:
      - nginx
      - elysium-stage
    image: registry.gitlab.com/haondt/cicd/registry/elysium-silo:0.0.5
    x-tl: x
    depends_on:
      - elysium-stage-postgres
      - elysium-stage-redis
    environment:
      VIRTUAL_HOST: elysium-stage-silo.chert
      VIRTUAL_PORT: 8080
    env_file:
      - ./elysium-stage/shared.env
    # deploy:
    #   replicas: 2
  elysium-stage-postgres:
    networks:
      - elysium-stage
      - wireguard
    image: postgres:16-alpine
    x-tl: x
    environment:
      POSTGRES_USER: "{{ elysium__stage__postgres__user }}"
      POSTGRES_PASSWORD: "{{ elysium__stage__postgres__password }}"
      PGDATA: /data/pgdata
    volumes:
      - elysium-postgres-data:/data
      - ./elysium-stage/postgresql-init.sql:/docker-entrypoint-initdb.d/postgresql-init.sql
  elysium-stage-redis:
    image: redis
    x-tl: x
    networks:
      - elysium-stage

networks:
  elysium-stage:

volumes:
  elysium-postgres-data:
