services:
  {{ COM_HAONDT_CONTAINER }}:
    container_name: "{{ COM_HAONDT_CONTAINER }}"
    labels:
      dev.haondt.host: "{{ haondt__host }}"
      dev.haondt.service: "{{ COM_HAONDT_CONTAINER }}"
    group_add:
      - "{{ haondt__pgid }}"
    environment:
      PGID: "{{ haondt__pgid }}"
      PUID: "{{ haondt__puid }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro

