services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.32.0@sha256:14c4697739979d67d097b9ff351f3bde1ee2b9511197cd55cb43dc1d41ad72c2
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer-data:/data
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: "portainer.{{ haondt__host }},portainer.{{ haondt__letsencrypt_host }}"
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
volumes:
  portainer-data:
