services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.30.1@sha256:efe1560377ccf297095fcdea7d44c4d79629a04a0098879b28a385262f14da71
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer-data:/data
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: "portainer.{{ haondt__host }},portainer.{{ haondt__letsencrypt_host }}"
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
volumes:
  portainer-data:
