services:
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer-data:/data
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: "portainer.flint"
      VIRTUAL_PORT: 9000
volumes:
  portainer-data:


