services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.31.2@sha256:eb7864f3cd4e31e6fe98db53fa5680bfbc627442a87b65770171ad8a822dec0b
    x-tl: ^:.!!?
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer-data:/data
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: "portainer.{{ haondt__host }},portainer.{{ haondt__letsencrypt_host }}"
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
volumes:
  portainer-data:
