services:
  website-haondt:
    image: registry.gitlab.com/haondt/cicd/registry/website:3.0.2
    networks:
      - rathole
    environment:
      RATHOLE_VIRTUAL_HOST: api.haondt.dev
      RATHOLE_VIRTUAL_PORT: 8000
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PATH: /haondt
      RATHOLE_VIRTUAL_DEST: /

