repositories:
  gcs_bucket: &gcs_backend
    type: gcs_bucket
    bucket: "{{ gcs__bucket }}"
    credentials: /config/gcs/credentials.json
  hzsb: &hzsb_backend
    type: rclone
    rclone_config:
      type: ftp
      host: "{{ hzsb__host }}"
      user: "{{ hzsb__user }}"
      pass: "{{ hzsb__password }}"
      port: 21
      explicit_tls: "true"

restic:
  common_password: &restic_password "{{ restic__password }}"
  small_data_max_snapshots: &small_mss 10
  large_data_max_snapshots: &large_mss 5

jobs:
  lldap:
    source: &lldap_source
      type: sqlite
      db_path: /backup/lldap/users.db
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *gcs_backend
        path: lldap
    schedule:
      cron: "0 0 * * *" # daily
  lldap_hz:
    source: *lldap_source
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *hzsb_backend
        path: lldap
    schedule:
      cron: "0 0 * * *" # daily
