services:
  glance:
    image: docker.io/glanceapp/glance:v0.8.2@sha256:fe80231892d3b7d7a2770a58d8058c190ac1c27eb806f5e2f09ee4cf101780eb
    x-tl: +!
    networks:
      - gabbro_nginx
      - glance
    volumes:
      - ./glance/config/:/app/config:ro
      - ./glance/assets:/app/assets:ro
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "glance.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp

networks:
  glance:
