services:
  glance:
    image: docker.io/glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    x-tl: +!
    networks:
      - gabbro_nginx
      - glance
    volumes:
      - ./glance/config/:/app/config:ro
      - ./glance/assets:/app/assets:ro
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "glance.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp
  glance-restic:
    image: ghcr.io/not-first/restic-glance-extension:latest@sha256:d1ad861ca2e8070721cec08915922aee5da32020516f7a38f970b61e1f610071
    x-tl: x
    volumes:
      - ./glance/credentials.json:/app/config/credentials.json
    networks:
      - glance
    env_file:
      - ./glance/glance-restic.env
  glance-github-graph:
    image: haumea/glance-github-graph:0.0.1
    x-tl: x
    networks:
      - glance
    environment:
      CACHE_TYPE: memory
      CACHE_ENABLED: true

networks:
  glance:
