services:
  glance:
    image: docker.io/glanceapp/glance:v0.7.8
    x-tl: +!
    networks:
      - gabbro_nginx
      - glance
    volumes:
      - ./glance/config/:/app/config:ro
      - ./glance/assets:/app/assets:ro
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "glance.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp
  glance-linktiles-proxy:
    image: nginx:mainline-alpine
    x-tl: +!
    networks:
      - glance
    volumes:
      - ./glance/linktiles-nginx.conf:/etc/nginx/nginx.conf

networks:
  glance:

