services:
  aeeo-wordpress-db:
    image: docker.io/library/mariadb:12@sha256:03a03a6817bb9eaa21e5aed1b734d432ec3f80021f5a2de1795475f158217545
    x-tl: ^!
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aeeowordpress
      MYSQL_DATABASE: aeeowordpress
      MYSQL_USER: aeeowordpress
      MYSQL_PASSWORD: aeeowordpress

  aeeo-wordpress:
    image: docker.io/library/wordpress:latest@sha256:d34b44296d24686bf1a9c70c435b1640202e8e97d824aad9997fc63a61ac5cbb
    x-tl: +!
    networks:
      - rathole
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_data/:/var/www/html
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 80
      RATHOLE_VIRTUAL_HOST: "{{ aeeo__domain }}"
      WORDPRESS_DB_HOST: aeeo-wordpress-db
      WORDPRESS_DB_USER: aeeowordpress
      WORDPRESS_DB_PASSWORD: aeeowordpress
      WORDPRESS_DB_NAME: aeeowordpress

networks:
  aeeo:

