services:
  aeeo-wordpress-db:
    image: docker.io/library/mariadb:12@sha256:8a061ef9813cf960f94a262930a32b190c3fbe5c8d3ab58456ef1df4b90fd5dc
    x-tl: ^!
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aeeowordpress
      MYSQL_DATABASE: aeeowordpress
      MYSQL_USER: aeeowordpress
      MYSQL_PASSWORD: aeeowordpress

  aeeo-wordpress:
    image: docker.io/library/wordpress:latest@sha256:12df37e2dd51401d350f3722a67d70316d29ff68c841f2d1d3f73f5979fc61d4
    x-tl: +!
    networks:
      - rathole
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_data/:/var/www/html
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 80
      RATHOLE_VIRTUAL_HOST: "{{ aeeo__domain }}"
      WORDPRESS_DB_HOST: aeeo-wordpress-db
      WORDPRESS_DB_USER: aeeowordpress
      WORDPRESS_DB_PASSWORD: aeeowordpress
      WORDPRESS_DB_NAME: aeeowordpress

networks:
  aeeo:

