services:
  aeeo-wordpress-db:
    image: docker.io/library/mariadb:12@sha256:a5af517d52262da1583cebe6b7c970d7bbeaf1f016938c2fc3cf2e95c52d8c08
    x-tl: ^!
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aeeowordpress
      MYSQL_DATABASE: aeeowordpress
      MYSQL_USER: aeeowordpress
      MYSQL_PASSWORD: aeeowordpress

  aeeo-wordpress:
    image: docker.io/library/wordpress:latest@sha256:0cb6d59b795408a3bc129e5ce9ca8741c3291714c9e03dbfc9d6beaa4b3753bf
    x-tl: +!
    networks:
      - rathole
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_data/:/var/www/html
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 80
      RATHOLE_VIRTUAL_HOST: "{{ aeeo__domain }}"
      WORDPRESS_DB_HOST: aeeo-wordpress-db
      WORDPRESS_DB_USER: aeeowordpress
      WORDPRESS_DB_PASSWORD: aeeowordpress
      WORDPRESS_DB_NAME: aeeowordpress

networks:
  aeeo:
