services:
  aeeo-wordpress-db:
    image: docker.io/library/mariadb:12@sha256:b30cc65b57a11a2e791ad5c06284e599fe9f1bf3fe9081a88d85bcf36389be4a
    x-tl: ^!
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aeeowordpress
      MYSQL_DATABASE: aeeowordpress
      MYSQL_USER: aeeowordpress
      MYSQL_PASSWORD: aeeowordpress

  aeeo-wordpress:
    image: docker.io/library/wordpress:latest@sha256:c5f075fe71c9120e769edbf761bcf20bf0b73d72d49dfde042a06aafcdfef08d
    x-tl: +!
    networks:
      - rathole
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_data/:/var/www/html
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 80
      RATHOLE_VIRTUAL_HOST: "{{ aeeo__domain }}"
      WORDPRESS_DB_HOST: aeeo-wordpress-db
      WORDPRESS_DB_USER: aeeowordpress
      WORDPRESS_DB_PASSWORD: aeeowordpress
      WORDPRESS_DB_NAME: aeeowordpress

networks:
  aeeo:
