services:
  aeeo-wordpress-db:
    image: mariadb:12
    x-tl: ^!
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aeeowordpress
      MYSQL_DATABASE: aeeowordpress
      MYSQL_USER: aeeowordpress
      MYSQL_PASSWORD: aeeowordpress

  aeeo-wordpress:
    image: wordpress:latest
    x-tl: +!
    networks:
      - rathole
      - aeeo
    volumes:
      - /mnt/celery/gabbro/aeeo/wordpress_data/:/var/www/html
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 80
      RATHOLE_VIRTUAL_HOST: "{{ aeeo__domain }}"
      WORDPRESS_DB_HOST: aeeo-wordpress-db
      WORDPRESS_DB_USER: aeeowordpress
      WORDPRESS_DB_PASSWORD: aeeowordpress
      WORDPRESS_DB_NAME: aeeowordpress

networks:
  aeeo:
