services:
  nginx:
    networks:
      - nginx
    image: docker.io/nginxproxy/nginx-proxy:latest@sha256:c4c7bf44f07b1274be499d87046bce2ae451d360df4aa2c52988a32110a126c6
    x-tl: +!
    ports:
      - 443:443
      - 80:80
    volumes: 
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - ./nginx/healthchecks.location.conf:/etc/nginx/vhost.d/hc.haondt.dev_location_override
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      NO_COLOR: yes

  nginx-acme:
    image: docker.io/nginxproxy/acme-companion:latest@sha256:f40d9d70b45c88926279e91b00507c12f8cf7dc9f33ab1876da48188b20fabaf
    x-tl: +!
    networks:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-acmesh:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "{{ cloudflare__default_email }}"
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Token: {{ cloudflare__token }}
        CF_Zone_ID: {{ cloudflare__zone_id }}
        CF_Account_ID: {{ cloudflare__account_id }}

networks:
  nginx:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acmesh:
