services:
  nginx:
    networks:
      - nginx
    image: docker.io/nginxproxy/nginx-proxy:latest@sha256:0fe58e5491bc39e4931adaae7c184627d02f732631475a5aae8159f77bd2eae6
    x-tl: +!
    ports:
      - 443:443
      - 80:80
    volumes: 
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - ./nginx/healthchecks.location.conf:/etc/nginx/vhost.d/hc.haondt.dev_location_override
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      NO_COLOR: yes

  nginx-acme:
    image: docker.io/nginxproxy/acme-companion:latest@sha256:d168c339f19502f47be3cad743ed0c0d3d03c63133a891567a2d224ce093eb54
    x-tl: +!
    networks:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-acmesh:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "{{ cloudflare__default_email }}"
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Token: {{ cloudflare__token }}
        CF_Zone_ID: {{ cloudflare__zone_id }}
        CF_Account_ID: {{ cloudflare__account_id }}

networks:
  nginx:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acmesh:
