services:
  nginx:
    networks:
      - nginx
    image: docker.io/nginxproxy/nginx-proxy:latest@sha256:6821b5e90de0dbf78623bb738f42c8025866a41fb0b1d4d790f70279c991c213
    x-tl: +!
    ports:
      - 443:443
      - 80:80
    volumes: 
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - ./nginx/healthchecks.location.conf:/etc/nginx/vhost.d/hc.haondt.dev_location_override
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      NO_COLOR: yes

  nginx-acme:
    image: docker.io/nginxproxy/acme-companion:latest@sha256:e190b3f89367a933ff3ae4435ee98f87d2d36c5ff367fcd39850390bd4b02ab1
    x-tl: +!
    networks:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-acmesh:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: "{{ cloudflare__default_email }}"
      ACME_CHALLENGE: DNS-01
      ACMESH_DNS_API_CONFIG: |-
        DNS_API: dns_cf
        CF_Token: {{ cloudflare__token }}
        CF_Zone_ID: {{ cloudflare__zone_id }}
        CF_Account_ID: {{ cloudflare__account_id }}

networks:
  nginx:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  nginx-acmesh:
