services:
  talos:
    image: registry.gitlab.com/haondt/cicd/registry/talos:0.1.0
    x-tl: x
    user: talos
    group_add:
      - "{{ gabbro__docker_group }}"
    networks:
      - rathole
      - talos
    env_file:
      - ./talos/talos.env
    environment:
      RATHOLE_VIRTUAL_HOST: api.haondt.dev
      RATHOLE_VIRTUAL_PORT: 8080
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PATH: /talos/
      RATHOLE_VIRTUAL_DEST: /
    volumes:
      - ./talos/id_rsa:/config/id_rsa
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: tmpfs
        target: /var/talos/git
        tmpfs:
          mode: 0777
          size: 64M
    logging:
      driver: syslog
      options:
        tag: docker-talos
  # talos-beta:
  #   image: registry.gitlab.com/haondt/cicd/registry/talos:main-71f4e923
  #   user: talos
  #   group_add:
  #     - "{{ gabbro__docker_group }}"
  #   networks:
  #     - gabbro_nginx
  #     - talos
  #   env_file:
  #     - ./talos/talos-beta.env
  #   environment:
  #     VIRTUAL_PORT: 8080
  #     VIRTUAL_HOST: "talos-beta.{{ haondt__letsencrypt_host }}"
  #     LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
  #     HTTPS_METHOD: nohttp
  #   volumes:
  #     - ./talos/id_rsa:/config/id_rsa
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - type: tmpfs
  #       target: /var/talos/git
  #       tmpfs:
  #         mode: 0777
  #         size: 64M
  #   logging:
  #     driver: syslog
  #     options:
  #       tag: docker-talos-beta
  talos-redis-insight:
    image: docker.io/redis/redisinsight:latest@sha256:b7aa18e73329ebb2e3d9e949b8d35193bf5415ef35c16fd9a50e6f832922b296
    x-tl: +!
    networks:
      - talos
      - gabbro_nginx
    environment:
      VIRTUAL_PORT: 5540
      VIRTUAL_HOST: "talos-redis.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp
    volumes:
      - talos-redis-insight-data:/data

  talos-redis:
    image: docker.io/library/redis:latest@sha256:acb90ced0bd769b7c04cb4c32c4494ba7b3e0ee068bdbfff0eeb0d31c2a21078
    x-tl: +!
    networks:
      - talos

networks:
  talos:
  gabbro_nginx:
    external: true
volumes:
  talos-redis-insight-data:

