services:
  talos:
    image: registry.gitlab.com/haondt/cicd/registry/talos:0.0.10
    user: talos
    group_add:
      - "{{ gabbro__docker_group }}"
    networks:
      - rathole
      - talos
    env_file:
      - ./talos/talos.env
    environment:
      RATHOLE_VIRTUAL_HOST: api.haondt.dev
      RATHOLE_VIRTUAL_PORT: 8080
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PATH: /talos/
      RATHOLE_VIRTUAL_DEST: /
    volumes:
      - ./talos/id_rsa:/config/id_rsa
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: tmpfs
        target: /var/talos/git
        tmpfs:
          mode: 0777
          size: 64M
    logging:
      driver: syslog
      options:
        tag: docker-talos

  talos-redis:
    networks:
      - talos
    image: redis

networks:
  talos:

