services:
  talos:
    build:
      context: ./talos
    networks:
      - rathole
    environment:
      RATHOLE_VIRTUAL_HOST: api.haondt.dev
      RATHOLE_VIRTUAL_PORT: 5000
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PATH: /talos/webhooks/
      RATHOLE_VIRTUAL_DEST: /

