services:
  rathole-marble-server:
    image: rapiz1/rathole:v0.5.0
    x-talos:
      skip: false
      bump: Minor
      strategy:
        digest: Push
        patch: Push
        minor: Push
    command: --server /app/config.toml 
    networks:
      - nginx
    volumes:
      - ./rathole/config.toml:/app/config.toml
    ports:
      - "{{ rathole__server__port }}:{{ rathole__server__port}}"
    environment:
      VIRTUAL_HOST: "vaultwarden.haondt.dev"
      VIRTUAL_PORT: 8080
      HTTPS_METHOD: nohttp
      LETSENCRYPT_HOST: "*.haondt.dev"
