services:
  rathole-marble-server:
    image: docker.io/rapiz1/rathole:v0.5.0@sha256:a31b9178e985d4a84f46d4c3af6aa200ee0c5e7f821c7075a1f6669fb77392b1
    x-talos:
      skip: false
      bump: Minor
      strategy:
        digest: Push
        patch: Push
        minor: Push
    command: --server /app/config.toml 
    networks:
      - nginx
    volumes:
      - ./rathole-marble/config.toml:/app/config.toml
    ports:
      - "{{ rathole__server__port }}:{{ rathole__server__port}}"
    environment:
      VIRTUAL_HOST: "glance.haondt.dev"
      VIRTUAL_PORT: 8080
      HTTPS_METHOD: nohttp
      LETSENCRYPT_HOST: "*.haondt.dev"
