services:
  loki:
    image: docker.io/grafana/loki:3.5.4@sha256:0b9846377113bc6a56eea2e56fe5963afdea2962178bd171190e30fa25157542
    x-tl: ^!
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - rathole
      - gabbro_grafana
      - loki
    volumes:
      - /mnt/celery/gabbro/loki:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml

networks:
  gabbro_grafana:
    external: true
  loki:
