services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - rathole
      - gabbro_grafana
      - loki
    volumes:
      - /mnt/celery/loki:/loki

networks:
  gabbro_grafana:
    external: true
  loki:
