services:
  loki:
    image: docker.io/grafana/loki:3.5.2@sha256:d0a95e651bb7d0a5a6468035c5b49c52f4678d90d598f853c06716bca102686b
    x-tl: ^!
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - rathole
      - gabbro_grafana
      - loki
    volumes:
      - /mnt/celery/gabbro/loki:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml

networks:
  gabbro_grafana:
    external: true
  loki:
