services:
  loki:
    image: docker.io/grafana/loki:3.5.5@sha256:31628519045e7f28692a7ae73b4a3fd293dccb425585ed5d16ceea3b5c9592e6
    x-tl: ^!
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - rathole
      - gabbro_grafana
      - loki
    volumes:
      - /mnt/celery/gabbro/loki:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml

networks:
  gabbro_grafana:
    external: true
  loki:
