services:
  loki:
    image: docker.io/grafana/loki:3.5.3@sha256:3165cecce301ce5b9b6e3530284b080934a05cd5cafac3d3d82edcb887b45ecd
    x-tl: ^!
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - rathole
      - gabbro_grafana
      - loki
    volumes:
      - /mnt/celery/gabbro/loki:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml

networks:
  gabbro_grafana:
    external: true
  loki:
