services:
  gsm:
    image: registry.gitlab.com/haondt/cicd/registry/gsm:v2-13382756
    container_name: gsm
    networks:
      - nginx
    volumes:
      - gsm-data:/data
    env_file:
      - ./gsm/gsm.env
    environment:
      VITRUAL_PORT: 8080
      VIRTUAL_HOST: "gsm.{{ flint__host }},gsm.{{ flint__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ flint__letsencrypt_host }}"

volumes:
  gsm-data:

