services:
  gsm:
    image: registry.gitlab.com/haondt/cicd/registry/gsm:v2-067e5d82
    container_name: gsm
    networks:
      - nginx
    volumes:
      - gsm-data:/data
    env_file:
      - ./gsm/gsm.env
    environment:
      VITRUAL_PORT: 8080
      VIRTUAL_HOST: "gsm.{{ haondt__host }},gsm.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"

volumes:
  gsm-data:

