services:
  mimir:
    image: grafana/mimir:2.15.1
    x-tl: +:.!!*
    command:
      - '--config.file=/etc/mimir/mimir.yml'
    networks:
      - rathole
      - gabbro_grafana
      - gabbro_nginx
      - mimir
    volumes:
      - ./mimir/mimir.yml:/etc/mimir/mimir.yml
      - /mnt/celery/gabbro/mimir/data/:/mimir
    environment:
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: "mimir.{{ haondt__letsencrypt_host }}"
      LETSENCRYPT_HOST: "*.{{ haondt__letsencrypt_host }}"
      HTTPS_METHOD: nohttp

networks:
  mimir:
