services:
  rathole-server:
    image: rapiz1/rathole:v0.5.0
    command: --server /app/config.toml
    networks:
      - rathole
      - nginx
    volumes:
      - ./rathole/config.toml:/app/config.toml
    environment:
      VIRTUAL_HOST: "*.cloud.haondt.dev"
      VIRTUAL_PORT: 8080
      HTTPS_METHOD: nohttp
      LETSENCRYPT_HOST: "*.cloud.haondt.dev"

  rathole-nginx:
    image: nginx:latest
    networks:
      - rathole
    ports:
      - "{{ rathole__server__port }}:{{ rathole__server__port}}"
    volumes:
      - ./rathole/nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  rathole:

