services:
  rathole-server:
    image: rapiz1/rathole:v0.5.0
    command: --server /app/config.toml 
    networks:
      - nginx
      - rathole
    volumes:
      - ./rathole/config.toml:/app/config.toml
    ports:
      - "{{ rathole__server__port }}:{{ rathole__server__port}}"
    environment:
      # VIRTUAL_HOST: "*.cloud.haondt.dev,api.haondt.dev"
      VIRTUAL_HOST: "immich.cloud.haondt.dev,microbin.cloud.haondt.dev,api.haondt.dev"
      VIRTUAL_PORT: 8080
      HTTPS_METHOD: nohttp
      LETSENCRYPT_HOST: "*.cloud.haondt.dev,api.haondt.dev"

networks:
  rathole:
