services:
  rathole-server:
    image: rapiz1/rathole:v0.5.0
    x-talos:
      skip: false
      bump: Minor
      strategy:
        digest: Push
        patch: Push
        minor: Push
      sync:
        role: parent
        group: rathole
        id: server
        children: [gabbro]
        digest: true
    command: --server /app/config.toml 
    networks:
      - nginx
      - rathole
    volumes:
      - ./rathole/config.toml:/app/config.toml
    ports:
      - "{{ rathole__server__port }}:{{ rathole__server__port}}"
    environment:
      VIRTUAL_HOST: "linktiles.cloud.haondt.dev,linkding.cloud.haondt.dev,immich.cloud.haondt.dev"
      VIRTUAL_PORT: 8080
      HTTPS_METHOD: nohttp
      LETSENCRYPT_HOST: "*.cloud.haondt.dev"

networks:
  rathole:

