services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.0.1@sha256:8286638680f0a38a7cb380be64ed77d1d1cfe6d0e0b843f64bff92b24289078d
    x-talos:
      skip: false
      bump: Major
      strategy:
        digest: Skip
        patch: Push
        minor: Push
        major: Prompt
      sync:
        role: parent
        group: immich
        id: server
        children: [ml]
        digest: false
    volumes:
      - /mnt/celery/gabbro/immich/upload:/usr/src/app/upload
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 2283
      RATHOLE_VIRTUAL_HOST: immich.cloud.haondt.dev
      RATHOLE_CONNECTION_TIMEOUT: 600s
      RATHOLE_MAX_BODY_SIZE: 50000M
      DB_PASSWORD: "{{ immich__postgres_password }}"
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich-db
      REDIS_HOSTNAME: immich-redis
    depends_on:
      - immich-redis
      - immich-db
    networks:
      - rathole
      - immich

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.0.1@sha256:45626a33361ef7ed361de41b0d2dc19e5949442cdf0a8eb64b157dc8a04e9855
    x-talos:
      skip: false
      sync:
        role: child
        group: immich
        id: ml
    networks:
      - immich
    volumes:
      - immich-model-cache:/cache

  immich-redis:
    image: docker.io/redis:6.2-alpine@sha256:77697a75da9f94e9357b61fcaf8345f69e3d9d32e9d15032c8415c21263977dc
    x-tl: ^!
    networks:
      - immich
    healthcheck:
      test: redis-cli ping || exit 1

  immich-db:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    x-tl: "@!"
    networks:
      - immich
    environment:
      POSTGRES_PASSWORD: "{{ immich__postgres_password }}"
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: HDD
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /mnt/celery/gabbro/immich/db:/var/lib/postgresql/data

volumes:
  immich-model-cache:

networks:
  immich:
