services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.139.2@sha256:ccfca8a87a65914ab23164efa1f6392940629a2a54ed71bce87049713d926426
    x-talos:
      skip: false
      bump: Major
      strategy:
        digest: Skip
        patch: Push
        minor: Push
        major: Prompt
      sync:
        role: parent
        group: immich
        id: server
        children: [ml]
        digest: false
    volumes:
      - /mnt/celery/gabbro/immich/upload:/usr/src/app/upload
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 2283
      RATHOLE_VIRTUAL_HOST: immich.cloud.haondt.dev
      RATHOLE_CONNECTION_TIMEOUT: 600s
      RATHOLE_MAX_BODY_SIZE: 50000M
      DB_PASSWORD: "{{ immich__postgres_password }}"
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich-db
      REDIS_HOSTNAME: immich-redis
    depends_on:
      - immich-redis
      - immich-db
    networks:
      - rathole
      - immich

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.139.2@sha256:735cacb990861a2e8e69ee71389d5551d4ca1db426b330c7c5a83ab28901b3b0
    x-talos:
      skip: false
      sync:
        role: child
        group: immich
        id: ml
    networks:
      - immich
    volumes:
      - immich-model-cache:/cache

  immich-redis:
    image: docker.io/redis:6.2-alpine@sha256:7fe72c486b910f6b1a9769c937dad5d63648ddee82e056f47417542dd40825bb
    x-tl: ^!
    networks:
      - immich
    healthcheck:
      test: redis-cli ping || exit 1

  immich-db:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    x-tl: "@!"
    networks:
      - immich
    environment:
      POSTGRES_PASSWORD: "{{ immich__postgres_password }}"
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: HDD
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /mnt/celery/gabbro/immich/db:/var/lib/postgresql/data

volumes:
  immich-model-cache:

networks:
  immich:

