services:
  healthchecks:
    image: healthchecks/healthchecks:v3.9
    x-tl: +:!!!?
    networks:
      - nginx
    restart: unless-stopped
    volumes:
      - healthchecks-data:/data
    environment:
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: hc.{{ haondt__host }}
      LETSENCRYPT_HOST: hc.{{ haondt__host }}
      HTTPS_METHOD: nohttp
      ALLOWED_HOSTS: hc.{{ haondt__host }}
      SITE_ROOT: https://hc.{{ haondt__host }}
      DEBUG: "False"
      APPRISE_ENABLED: "True"
      PING_ENDPOINT: https://hc.{{ haondt__host }}/ping/
      REGISTRATION_OPEN: "False"
      SECRET_KEY: "{{ healthchecks__secret_key }}"
      DB: sqlite
      DB_NAME: /data/hc.sqlite

volumes:
  healthchecks-data:
