services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    x-tl: +!
    networks:
      - nginx
    restart: unless-stopped
    environment:
      # nginx
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: hc.{{ haondt__host }}
      LETSENCRYPT_HOST: hc.{{ haondt__host }}
      HTTPS_METHOD: nohttp

      # healthchecks
      ALLOWED_HOSTS: hc.{{ haondt__host }}
      SITE_ROOT: https://hc.{{ haondt__host }}
      DEBUG: "False"
      APPRISE_ENABLED: "True"
      PING_ENDPOINT: https://hc.{{ haondt__host }}/ping/
      REGISTRATION_OPEN: "False"
      SECRET_KEY: "{{ healthchecks__secret_key }}"
      SITE_NAME: Haondt Healthchecks

      # lscr.io
      SUPERUSER_EMAIL: "{{ healthchecks__superuser_email }}"
      SUPERUSER_PASSWORD: "{{ healthchecks__superuser_password }}"
      TZ: America/Edmonton
