- type: extension
  url: http://glance-github-graph:8080/graph/haondt
  allow-potentially-dangerous-html: true
  parameters:
    background-color: "#1d2025"
    primary-color: "#f3afaf"
    svg-height: 160
    font-size: 10
    transition-hue: false
