# yamllint disable rule:comments-indentation
---
###############################################################################
##                           Authelia Configuration                          ##
###############################################################################

identity_validation:
  reset_password:
    jwt_secret: "{{ authelia__jwt_secret }}"

totp:
  disable: false
  issuer: auth.haondt.dev

authentication_backend:
  password_reset:
    disable: false
  ldap:
    implementation: lldap
    address: ldap://lldap:3890
    base_dn: dc=haondt,dc=dev
    user: uid={{ authelia__lldap_username }},ou=people,dc=haondt,dc=dev
    password: "{{ authelia__lldap_password }}"

storage:
  encryption_key: "{{ authelia__encryption_key }}"
  local:
    path: /config/db.sqlite3

session:
  secret: "{{ authelia__session_secret }}"
  cookies:
    - domain: haondt.dev
      authelia_url: https://auth.haondt.dev

notifier:
  smtp:
    address: 'smtp.mailgun.org'
    username: 'authelia@notify.haondt.dev'
    password: "{{ authelia__mailgun__password }}"
    sender: 'Authelia <authelia@notify.haondt.dev>'

access_control:
  default_policy: deny
  rules:
    - domain: '*.cloud.haondt.dev'
      policy: two_factor

identity_providers:
  oidc:
    hmac_secret: "{{ authelia__oidc__hmac_secret }}"
    jwks:
      - key_id: 'authelia'
        algorithm: 'RS256'
        use: 'sig'
        key: {{ secret "/config/secrets/oidc/jwks/authelia.key" | mindent 10 "|" | msquote }}
        certificate_chain: {{ secret "/config/secrets/oidc/jwks/authelia.crt" | mindent 10 "|" | msquote }}
    cors:
      allowed_origins:
        - 'https://immich.cloud.haondt.dev'
    clients:
      - client_id: immich
        client_name: Immich OIDC
        client_secret: "{{ authelia__oidc__immich__client_secret }}"
        redirect_uris:
          - https://auth.haondt.dev/
          - https://auth.haondt.dev/oauth2/callback
          - https://immich.cloud.haondt.dev/oauth2/callback
          - https://immich.cloud.haondt.dev/auth/login
          - https://immich.cloud.haondt.dev/user-settings
          - https://immich.cloud.haondt.dev
          - app.immich:/ # required for immich < v1.113.0
          - app.immich:///oauth-callback # required since immich v1.113.0
          - https://immich.cloud.haondt.dev/api/oauth/mobile-redirect
        grant_types:
          - refresh_token
          - authorization_code
        response_modes:
          - form_post
          - query
          - fragment
        authorization_policy: two_factor

