services:
  authelia:
    image: docker.io/authelia/authelia:4.39@sha256:8f428b06bb07bb978c10477527634f19ef3b049c9c87321fda14e24d8fc4c535
    x-tl: ^!
    volumes:
      - /srv/data/authelia:/config
      - ./authelia/config.yml:/config/configuration.yml
      - ./authelia/oidc-jwks-certificate.key:/config/secrets/oidc/jwks/authelia.key
    networks:
      - authelia
      - nginx
      - alloy
    environment:
      VIRTUAL_HOST: "auth.haondt.dev"
      VIRTUAL_PORT: 9091
      HTTPS_METHOD: nohttp
      LETSENCRYPT_HOST: "auth.haondt.dev"
      X_AUTHELIA_CONFIG_FILTERS: template

  lldap:
    image: docker.io/lldap/lldap:stable@sha256:2a8454b668c1aba7157e832eab0e242e1e7eb5fb7591d7e7774ba05286511ca8
    x-tl: +!
    networks:
      - wireguard
      - authelia
    volumes:
      - /srv/data/lldap:/data
    environment:
      LLDAP_JWT_SECRET:  "{{ lldap__jwt_secret }}"
      LLDAP_KEY_SEED: "{{ lldap__key_seed }}"
      LLDAP_LDAP_BASE_DN: dc=haondt,dc=dev

networks:
  authelia:


