services:
  gabbro-bot:
    image: registry.gitlab.com/haondt/cicd/registry/gabbro-bot:latest@sha256:779305a08ab263c08cefcd6dab9c158c86526b281dfd0a576e5fa26517af7905
    x-tl: +!
    container_name: gabbro_bot
    environment:
      COM_GABBRO_DISCORD_TOKEN: "{{ DISCORD_TOKEN }}"
      COM_GABBRO_DOCKER_HOST: "{{ TARGET_HOST }}"
      COM_GABBRO_DOCKER_USER: "{{ TARGET_USER }}"
      COM_GABBRO_DOCKER_PASSWORD: "{{ TARGET_PASSWORD }}"
      COM_GABBRO_DOCKER_PATH: /srv/deploy/gabbro
