services:
  microbin-cloud:
    image: docker.io/danielszabo99/microbin:2.0.4@sha256:c5bd4643135540a68a2846950fe4f65f3bcc94b62ed7c7644e563dfde6f1732c
    x-tl: "+!"
    environment:
      RATHOLE_INCLUDE:
      RATHOLE_VIRTUAL_PORT: 8080
      RATHOLE_VIRTUAL_HOST: microbin.cloud.haondt.dev

      # see https://github.com/szabodanika/microbin/blob/master/.env
      MICROBIN_HIDE_LOGO: true
      MICROBIN_PRIVATE: true
      MICROBIN_GC_DAYS: 0
      MICROBIN_QR: true
      MICROBIN_ETERNAL_PASTA: true
      MICROBIN_DEFAULT_EXPIRY: 24hour
      MICROBIN_LIST_SERVER: false
    networks:
      - rathole
