services:
  cdn-cache:
    image: docker.io/library/nginx:mainline-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10
    x-tl: +!
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/celery/gabbro/cdn/cache_data/:/var/cache/nginx
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: cdn.haondt.dev
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: cdn.haondt.dev
      HTTPS_METHOD: nohttp
