services:
  cdn-cache:
    image: docker.io/library/nginx:mainline-alpine@sha256:56c93b2a17e185519a5f420173f899783f0890da60463011c59ddbb904f02093
    x-tl: +!
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/celery/gabbro/cdn/cache_data/:/var/cache/nginx
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: cdn.haondt.dev
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: cdn.haondt.dev
      HTTPS_METHOD: nohttp
