services:
  cdn-cache:
    image: docker.io/library/nginx:mainline-alpine@sha256:d67ea0d64d518b1bb04acde3b00f722ac3e9764b3209a9b0a98924ba35e4b779
    x-tl: +!
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/celery/gabbro/cdn/cache_data/:/var/cache/nginx
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: cdn.haondt.dev
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: cdn.haondt.dev
      HTTPS_METHOD: nohttp
