services:
  cdn-cache:
    image: docker.io/library/nginx:mainline-alpine@sha256:2459838ed006e699c252db374550c91490068bbf3b35fa8b9d29bfe0e31b8b95
    x-tl: +!
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/celery/gabbro/cdn/cache_data/:/var/cache/nginx
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: cdn.haondt.dev
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: cdn.haondt.dev
      HTTPS_METHOD: nohttp
