services:
  cdn-cache:
    image: docker.io/library/nginx:mainline-alpine@sha256:42a516af16b852e33b7682d5ef8acbd5d13fe08fecadc7ed98605ba5e3b26ab8
    x-tl: +!
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/celery/gabbro/cdn/cache_data/:/var/cache/nginx
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: cdn.haondt.dev
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: cdn.haondt.dev
      HTTPS_METHOD: nohttp
