[client]
remote_addr = "{{ rathole__server__host }}:{{ rathole__server__port }}"

[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "{{ rathole__server__public_key }}"

[client.services.haondt]
token = "{{ rathole__haondt__token }}"
local_addr = "rathole-nginx:80"

[client.services.loki]
token = "{{ rathole__loki__token }}"
local_addr = "loki:3100"

[client.services.mimir]
token = "{{ rathole__mimir__token }}"
local_addr = "mimir:8080"
