services:
  rathole-client:
    image: rapiz1/rathole:v0.5.0
    command: --client /app/config.toml
    networks:
      - rathole
    volumes:
      - ./rathole/config.toml:/app/config.toml

networks:
  rathole:

