services:
  rathole-client:
    image: rapiz1/rathole:v0.5.0
    x-talos:
      sync:
        role: child
        group: rathole
        id: gabbro
    command: --client /app/config.toml
    networks:
      - rathole
    volumes:
      - ./rathole/config.toml:/app/config.toml

  rathole-nginx:
    image: nginx:latest
    volumes:
      - /mnt/celery/gabbro/rathole/nginx:/etc/nginx/conf.d:ro
    networks:
      - rathole
  
  rathole-docker-gen:
    image: jwilder/docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./rathole/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /mnt/celery/gabbro/rathole/nginx:/etc/nginx
    command: -notify-sighup rathole-nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/nginx.conf

networks:
  rathole:

