services:
  rathole-client:
    image: rapiz1/rathole:v0.5.0
    command: --client /app/config.toml
    networks:
      - rathole
    volumes:
      - ./rathole/config.toml:/app/config.toml

  # rathole-nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./rathole/nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - rathole
  
  rathole-docker-gen:
    image: jwilder/docker-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./rathole/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./rathole/nginx:/etc/nginx
    command: -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/nginx.conf

networks:
  rathole:

