services:
  rathole-client:
    image: rapiz1/rathole
    command: rathole --client /app/config.toml
    networks:
      - rathole
    volumes:
      - ./rathole/config.toml:/app/config.toml

networks:
  rathole:

