repositories:
  gcs_bucket: &gcs_backend
    type: gcs_bucket
    bucket: "{{ gcs__bucket }}"
    credentials: /config/gcs/credentials.json
  hzsb: &hzsb_backend
    type: rclone
    rclone_config:
      type: ftp
      host: "{{ hzsb__host }}"
      user: "{{ hzsb__user }}"
      pass: "{{ hzsb__password }}"
      port: 21
      explicit_tls: "true"

restic:
  common_password: &restic_password "{{ restic__password }}"
  small_data_max_snapshots: &small_mss 10
  large_data_max_snapshots: &large_mss 5

jobs:
  gsm:
    source: &gsm_source
      type: http
      url: https://gsm.flint.local.haondt.dev/api/export-data
      method: get
      ext: json
      auth:
        bearer: "{{ gsm__api_key }}"
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *gcs_backend
        path: gsm
    schedule:
      cron: "0 0 * * *" # daily
  gsm_hz:
    source: *gsm_source
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *hzsb_backend
        path: gsm
    schedule:
      cron: "0 6 * * *" # daily
  syncthing:
    source: &syncthing_source
      type: local
      path: /backup/syncthing
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *gcs_backend
        path: syncthing
    schedule:
      cron: "0 0 * * *" # daily
  syncthing_hz:
    source: *syncthing_source
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *hzsb_backend
        path: syncthing
    schedule:
      cron: "0 6 * * *" # daily
  vaultwarden:
    source: &vaultwarden_source
      type: sqlite
      db_path: /backup/vaultwarden/db.sqlite3
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *gcs_backend
        path: vaultwarden
    schedule:
      cron: "0 0 * * *" # daily
  vaultwarden_hz:
    source: *vaultwarden_source
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *hzsb_backend
        path: vaultwarden
    schedule:
      cron: "0 6 * * *" # daily
  immich:
    source:
      type: local
      path: /backup/immich
    repository:
      password: *restic_password
      max_snapshots: *large_mss
      backend:
        <<: *hzsb_backend
        path: immich
    schedule:
      cron: "0 12 1,15 * 2" # 2x per month
  grafana:
    source:
      type: http
      targets:
        access_logs: &grafana_dashboard
          url: http://grafana:3000/api/dashboards/uid/eeddz8aq0epdsf
          ext: json
          auth:
            bearer: "{{ grafana__api_key }}"
          transform:
            - jq: .dashboard
        charon_ops: 
          <<: *grafana_dashboard
          url: http://grafana:3000/api/dashboards/uid/dedkhah824zr4d
    repository:
      password: *restic_password
      max_snapshots: *small_mss
      backend:
        <<: *gcs_backend
        path: grafana
    schedule:
      after: 0s
      cron: "0 0 * * *" # daily

