services:
  charon-v2:
    image: registry.gitlab.com/haondt/cicd/registry/charon:2.0.0
    volumes:
      - ./charon/credentials.json:/config/gcs/credentials.json
      - ./charon/charon.yml:/config/charon.yml
      - /mnt/celery/gabbro/syncthing/data/:/backup/syncthing/
      - /mnt/celery/gabbro/vaultwarden/db.sqlite3:/backup/vaultwarden/db.sqlite3
