services:
  {{ COM_HAONDT_CONTAINER }}:
    container_name: "{{ COM_HAONDT_CONTAINER }}"
    group_add:
      - "{{ haondt__pgid }}"
    labels:
      com.gabbro.host: gabbro
      com.gabbro.service: "{{ COM_HAONDT_CONTAINER }}"
      dev.haondt.host: gabbro
      dev.haondt.service: "{{ COM_HAONDT_CONTAINER }}"
    volumes:
      - /etc/localtime:/etc/localtime:ro

 

